## Data Ingestion

#### Imports

In [1]:
from pathlib import Path
import pandas as pd
import requests

#### Defining dataset URLs for downloading

In [2]:
PARQUET_URL = "https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-01.parquet"
LOOKUP_URL = "https://d37ci6vzurychx.cloudfront.net/misc/taxi_zone_lookup.csv"

#### Downloading and saving datasets to correct folder

In [3]:
parquet_path = Path("../data/raw/tlc/yellow_tripdata_2023-01.parquet")
lookup_path = Path("../data/raw/lookup/taxi_zone_lookup.csv")

In [4]:
def download_file(url, path):
    if path.exists():
        print(f"{path} already exists")
        return
    
    response = requests.get(url)
    response.raise_for_status()

    with open(path, "wb") as f:
        f.write(response.content)

    print(f"Downloaded {path}")

In [5]:
download_file(PARQUET_URL, parquet_path)
download_file(LOOKUP_URL, lookup_path)

Downloaded ..\data\raw\tlc\yellow_tripdata_2023-01.parquet
Downloaded ..\data\raw\lookup\taxi_zone_lookup.csv

#### Loading datasets

In [6]:
tripdata = pd.read_parquet(parquet_path)
zone_lookup = pd.read_csv(lookup_path)

In [12]:
tripdata.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [13]:
zone_lookup.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

Row Counts

In [7]:
print("Trip dataset rows:", len(tripdata))
print("Zone lookup rows:", len(zone_lookup))

Trip dataset rows: 3066766
Zone lookup rows: 265

Column List

In [8]:
print("Tripdata columns:")
print(tripdata.columns.tolist())

print("\nZone lookup columns:")
print(zone_lookup.columns.tolist())

Tripdata columns:
['VendorID', 'tpep_pickup_datetime', 'tpep_dropoff_datetime', 'passenger_count', 'trip_distance', 'RatecodeID', 'store_and_fwd_flag', 'PULocationID', 'DOLocationID', 'payment_type', 'fare_amount', 'extra', 'mta_tax', 'tip_amount', 'tolls_amount', 'improvement_surcharge', 'total_amount', 'congestion_surcharge', 'airport_fee']

Zone lookup columns:
['LocationID', 'Borough', 'Zone', 'service_zone']

Data Types

In [9]:
print("Tripdata data types:")
print(tripdata.dtypes)

print("\nZone lookup data types:")
print(zone_lookup.dtypes)

Tripdata data types:
VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
dtype: object

Zone lookup data types:
LocationID       int64
Borough         object
Zone            object
service_zone    object
dtype: object

Number of nulls per column (Top 10)

In [10]:
trip_nulls = tripdata.isna().sum().sort_values(ascending=False)
lookup_nulls = zone_lookup.isna().sum().sort_values(ascending=False)

print("Top 10 null counts in trip dataset:")
print(trip_nulls.head(10))

Top 10 null counts in trip dataset:
store_and_fwd_flag       71743
RatecodeID               71743
passenger_count          71743
airport_fee              71743
congestion_surcharge     71743
VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
DOLocationID                 0
PULocationID                 0
dtype: int64

In [11]:
print("\nNull counts in lookup table:")
print(lookup_nulls)

Null counts in lookup table:
service_zone    2
Borough         1
Zone            1
LocationID      0
dtype: int64